name: Retos Automatización

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-automation-suite:
    name: Ejecución de Pruebas
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: 1. Descargar Código del Repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 3. Levantar Infraestructura de Kafka (Docker)
        run: |
          docker compose up -d
          echo "Esperando que la aplicación esté lista..."

      - name: 4. Instalar Dependencias de Pruebas (Playwright)
        run: |
          cd ../test
          npm ci
          npm run install:browsers:ci

      - name: 5. Ejecutar pruebas Playwright
        run: |
          cd tests
          npm run test

